<!-- Room Details to do
1. Vacate room after reservation date reaches
2. Only admin can delete room
3. view room reservations history
4. Be able to download that history
5. revenue generated by that room, download report

 -->
<?php
session_start();
require_once('config/config.php');
require_once('config/checklogin.php');
checklogin();

/* Update Room Details */
if (isset($_POST['Update_Room'])) {
    $room_id = $_POST['room_id'];
    $room_number = $_POST['room_number'];
    $room_type = $_POST['room_type'];
    $room_rate = $_POST['room_rate'];

    $query = "UPDATE  rooms SET room_number =?, room_type =?, room_rate =? WHERE room_id = ?";
    $stmt = $mysqli->prepare($query);
    $rc = $stmt->bind_param('ssss', $room_number, $room_type, $room_rate, $room_id);
    $stmt->execute();
    if ($stmt) {
        $success = "$room_number - $room_type Updated";
    } else {
        $info = "Please Try Again Or Try Later";
    }
}

/* Vacate Room */
if (isset($_POST['Vacate_Room'])) {
    $room_id = $_POST['room_id'];
    $room_status = 'Vacant';

    $query = "UPDATE  rooms SET room_status =? WHERE room_id = ?";
    $stmt = $mysqli->prepare($query);
    $rc = $stmt->bind_param('ss', $room_status, $room_id);
    $stmt->execute();
    if ($stmt) {
        $success = "Room Vacated";
    } else {
        $info = "Please Try Again Or Try Later";
    }
}


require_once('partials/head.php');
?>

<body class="theme-red">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <?php require_once('partials/loader.php'); ?>
    </div>

    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>


    <!-- Top Bar -->
    <?php require_once('partials/navigation.php'); ?>

    <!-- Left Sidebar -->
    <?php
    require_once('partials/sidebar.php');
    $view = $_GET['view'];
    $ret = "SELECT * FROM rooms WHERE room_id = '$view'";
    $stmt = $mysqli->prepare($ret);
    $stmt->execute(); //ok
    $res = $stmt->get_result();
    while ($room = $res->fetch_object()) {
    ?>
        <section class="content profile-page">
            <div class="container-fluid">
                <div class="block-header">
                    <div class="row">
                        <div class="col-lg-12 col-md-6 col-sm-7">
                            <h2><?php echo $room->room_number; ?> Details</h2>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="dashboard">Dashboard</a></li>
                                <li class="breadcrumb-item"><a href="">Reservations</a></li>
                                <li class="breadcrumb-item"><a href="modules_bookings_rooms">Guest Rooms</a></li>
                                <li class="breadcrumb-item active"><?php echo $room->room_number; ?></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row clearfix">
                    <div class="col-md-12">
                        <div class="boxs-simple">
                            <div class="profile-header">
                                <div class="profile_info">
                                    <div class="profile-image"> <img src="assets/images/Membership_Package" alt=""> </div>
                                    <h4 class="mb-0"><strong><?php echo $room->room_number; ?></strong></h4>
                                    <span class="">Category: <?php echo $room->room_type;  ?></span><br>
                                    <span class="">Status: <?php echo $room->room_status;  ?></span><br>
                                    <span class="">Reservation Rate: <?php echo $room->room_rate;  ?></span><br>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-1">
                        <div class="card">
                            <div class="body">
                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs">
                                    <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#room_settings">Room Settings</a></li>
                                    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#room_reservations_history">Room Reservation History</a></li>
                                    <li class="nav-item"><a class="nav-link " data-toggle="tab" href="#room_revenue">Room Revenue</a></li>

                                    <?php
                                    $user_access_level = $_SESSION['user_access_level'];
                                    /* Only Show This If Access Level Is Admin */
                                    if ($user_access_level == 'Administrator') {
                                        if ($room->room_status != 'Vacant') {
                                    ?>
                                            <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#vacate_room">Vacate Room</a></li>
                                        <?php } ?>
                                        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#delete_room">Delete Room</a></li>
                                    <?php } ?>
                                </ul>

                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane active" id="room_settings">
                                        <div class="wrap-reset">

                                        </div>
                                    </div>

                                    <div role="tabpanel" class="tab-pane" id="room_reservations_history">

                                    </div>

                                    <div role="tabpanel" class="tab-pane" id="room_revenue">

                                    </div>


                                    <div role="tabpanel" class="tab-pane" id="vacate_room">
                                        <div class="row clearfix">
                                            <div class="modal-body">
                                                <div class="row clearfix">
                                                    <br>
                                                    <h2 class="card-inside-title  text-danger text-center">
                                                        Heads Up!, you are about to vacate guest in room number : <?php echo $room->room_number; ?>.
                                                    </h2>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="d-flex justify-content-center">
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#vacate_modal">Vacate Room</button>
                                        </div>
                                    </div>

                                    <div role="tabpanel" class="tab-pane" id="delete_room">
                                        <div class="row clearfix">
                                            <div class="modal-body">
                                                <div class="row clearfix">
                                                    <br>
                                                    <h2 class="card-inside-title  text-danger text-center">
                                                        Heads Up!, you are about to delete room number : <?php echo $room->room_number; ?>.
                                                        This action is reversible, the system will permanently delete this room
                                                        records and any other related records too.
                                                    </h2>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="d-flex justify-content-center">
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#delete_modal">Delete Account</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Delete Account Modal -->
        <div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">CONFIRM</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-center text-danger">
                        <h4>Delete <?php echo $room->room_number; ?> ?</h4>
                        <br>
                        <p>Heads Up, You are about to delete room number: <?php echo $room->room_number; ?>. This action is irrevisble.</p>
                        <button type="button" class="text-center btn btn-success" data-dismiss="modal">No</button>
                        <a href="modules_bookings_rooms?delete=<?php echo $room->room_id; ?>" class="text-center btn btn-danger"> Delete </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Vacate Room Modal -->
        <div class="modal fade" id="vacate_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">CONFIRM</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body text-center text-danger">
                        <h4>Vacate Room Number : <?php echo $room->room_number; ?> ?</h4>
                        <br>
                        <p>Heads Up, You are about to vacate a guest in room number: <?php echo $room->room_number; ?>.</p>
                        <button type="button" class="text-center btn btn-success" data-dismiss="modal">No</button>
                        <a href="modules_bookings_room?view=<?php echo $room->room_id; ?>&vacate=<?php echo $room->room_id; ?>" class="text-center btn btn-danger"> Delete </a>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php require_once('partials/scripts.php'); ?>
</body>

</html>